#
# Copyright 2017-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed 
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. See the License for the specific language governing 
# permissions and limitations under the License.
#

AWSTemplateFormatVersion: 2010-09-09
Description: Sets up the Datalake for the Compliance-as-Code. 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Compliance-as-Code Dalatake Configuration
        Parameters:
         - CentralizedS3BucketConfig
         - CentralizedS3BucketComplianceEventName

Parameters:
  CentralizedS3BucketConfig:
    ConstraintDescription: Enter DNS-compliant prefix
    Description: Bucket prefix where Config logs are stored. A dash and the account ID (12-digit) will be appended to the name.
    MaxLength: 63
    MinLength: 10
    Type: String

  CentralizedS3BucketComplianceEventName:
    ConstraintDescription: Enter DNS-compliant prefix
    Description: Bucket prefix where Compliance Event are stored. A dash and the account ID (12-digit) will be appended to the name.
    MaxLength: 63
    MinLength: 10
    Type: String

  FolderWhereFireHoseIsSending:
    Description: Folder in the Centralized Bucket of Compliance event, where Firehose loads the data.
    Default: compliance-as-code-events
    MaxLength: 63
    MinLength: 10
    Type: String

  KeyListGeneratedByFirehose:
    Description: List of the key in the json generated by Kinesis Firehose.
    Type: String

  ColumnKeyList:
    Description: List of the columns in Athena.
    Type: String
  
  AccountList:
    Description: Verify if Account List is configured.
    Type: String

  LocationAccountListCSV:
    Description: Location where the account_list.csv is stored.
    Type: String

Conditions:
  AccountList: !Not [ !Equals [!Ref AccountList, "none"]]

Resources:
  GlueDatabaseComplianceAsCode:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: complianceascode
      CatalogId: !Ref 'AWS::AccountId'

  GlueTableConfigEvents:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabaseComplianceAsCode
      TableInput:
        Name: events
        Owner: hadoop
        Parameters: {
           "EXTERNAL": "TRUE",
           "classification": "json",
           "compressionType": "gzip",
           "transient_lastDdlTime": "1521161215",
           "typeOfData": "file"
        }
        PartitionKeys:
        - !Ref 'AWS::NoValue'
        StorageDescriptor:
          NumberOfBuckets: "-1"
          BucketColumns:
            - !Ref 'AWS::NoValue'
          Parameters: {}
          SkewedInfo:
            SkewedColumnNames: []
            SkewedColumnValues: []
            SkewedColumnValueLocationMaps: {}
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: configrulearn
            Type: string
          - Name: enginerecordedtime
            Type: string
          - Name: configrulename
            Type: string
          - Name: resourcetype
            Type: string
          - Name: resourceid
            Type: string
          - Name: resultrecordedtime
            Type: string
          - Name: configruleinvokedtime
            Type: string
          - Name: accountid
            Type: string
          - Name: awsregion
            Type: string
          - Name: annotation
            Type: string
          - Name: compliancetype
            Type: string
          - Name: whitelistedcompliancetype
            Type: string
          - Name: availability
            Type: string
          - Name: baseline
            Type: string
          - Name: confidentiality
            Type: string
          - Name: otherregionsbaseline
            Type: string
          - Name: pci
            Type: string
          - Name: rulecriticity
            Type: string
          Location: !Join ["", ["s3://", !Ref CentralizedS3BucketComplianceEventName, "-", !Ref "AWS::AccountId", "/", !Ref FolderWhereFireHoseIsSending, "/"]]
          SerdeInfo:
            Parameters:
              paths: "ConfigRuleArn,EngineRecordedTime,ConfigRuleName,ResourceType,ResourceId,ResultRecordedTime,ConfigRuleInvokedTime,AccountId,AwsRegion,Annotation,ComplianceType,WhitelistedComplianceType,availability,baseline,confidentiality,otherregionsbaseline,pci,rulecriticity"
              serialization.format: "1"
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        TableType: EXTERNAL_TABLE

  GlueTableConfig:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabaseComplianceAsCode
      TableInput:
        Name: config
        Owner: hadoop
        Parameters: {
          "EXTERNAL": "TRUE"
        }
        PartitionKeys:
        - !Ref 'AWS::NoValue'
        StorageDescriptor:
          NumberOfBuckets: "-1"
          BucketColumns:
            - !Ref 'AWS::NoValue'
          Parameters: {}
          SkewedInfo:
            SkewedColumnNames: []
            SkewedColumnValues: []
            SkewedColumnValueLocationMaps: {}
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat"
          Columns:
          - Name: fileversion
            Type: string
          - Name: configsnapshotid
            Type: string
          - Name: configurationitems
            Type: "array<struct<relatedEvents:string,relationships:string,configuration:string,supplementaryConfiguration:string,tags:string,configurationItemVersion:string,configurationItemCaptureTime:string,configurationStateId:string,awsAccountId:string,configurationItemStatus:string,resourceType:string,resourceId:string,resourceName:string,ARN:string,awsRegion:string,availabilityZone:string,configurationStateMd5Hash:string,resourceCreationTime:string>>"
          Location: !Join [ "", [ "s3://", !Ref CentralizedS3BucketConfig, "-", !Ref 'AWS::AccountId', "/"]]
          SerdeInfo:
            Parameters:
              serialization.format: "1"
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        TableType: EXTERNAL_TABLE

  GlueTableConfigAccoountList:
      Type: AWS::Glue::Table
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: !Ref GlueDatabaseComplianceAsCode
        TableInput:
          Name: accountlist
          Owner: hadoop
          Parameters: {
            "EXTERNAL": "TRUE"
          }
          PartitionKeys:
          - !Ref 'AWS::NoValue'
          StorageDescriptor:
            NumberOfBuckets: "-1"
            BucketColumns:
              - !Ref 'AWS::NoValue'
            Parameters: {}
            SkewedInfo:
              SkewedColumnNames: []
              SkewedColumnValues: []
              SkewedColumnValueLocationMaps: {}
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            Columns:
            - Name: accountname
              Type: string
            - Name: accountid
              Type: string
            - Name: owneremails
              Type: string
            - Name: tag1
              Type: string
            - Name: tag2
              Type: string
            Location: !Join ["", ["s3://", !Ref LocationAccountListCSV, "/csv"]]
            SerdeInfo:
              Parameters:
                separatorChar: ","
                serialization.format: "1"
              SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
          TableType: EXTERNAL_TABLE
